msrv = "1.70.0"
warn-on-all-wildcard-imports = true
disallowed-names = ["foo", "baz", "quux"]
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 7
type-complexity-threshold = 250
single-char-binding-names-threshold = 4
trivial-copy-size-limit = 128
pass-by-value-size-limit = 256
too-many-lines-threshold = 100
avoid-breaking-exported-api = true
suppress-restriction-lint-in-const = false